### ISSUE TITLE
Custom converter is not used when called from another converter

### ISSUE THREAD

**Issue by SanderBenschop** [42BV/beanmapper-spring#38]
Consider the following scenario.

Let's say we have a custom converter called `ParticipationResultConverter`. If this converter asks the beanmapper to convert a User to a UserResult, and there is also a custom converter for that User, the custom converter is not called when the conversion is requested on the 'top level'. But it is done if that user is in a list for instance.

Example:

```java
public class ProgramResultConverter extends SimpleBeanConverter<Program, ProgramResult> {

    @Override
    protected ProgramResult doConvert(Program source) {
		// This uses the default converter
		BasicUserResult convertedUser1 = beanMapper.map(user, BasicUserResult.class);

		// This uses the custom converter
		List<User> users = Arrays.asList(user);
		List<BasicUserResult> convertedUsers = beanMapper.map(users, BasicUserResult.class);
		BasicUserResult convertedUser2 = convertedUsers.get(0);
	}
}
```

If I need to clarify further, please let me know.

**Comment by marcus-talbot42** [comment]
The problem is a matter of configuration. The CoreConfiguration is expected to disallow the use of custom converters, unless explicitly set to allow it, using BeanMapperBuilder#setConverterChoosable(boolean).

The problem in the example above can be solved by using the following:

`BasicUserResult convertedUser1 = beanMapper.wrap().setConverterChoosable(true).build().map(user, BasicUserResult.class);`

The option to allow custom converters for list items is enabled by default, which is why the example using the List does use the correct custom converter.
